# Generated by Django 4.0.3 on 2022-06-09 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Categoria', max_length=100)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'unique_together': {('descripcion', 'uc')},
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('factura_numero', models.CharField(help_text='Factura N°', max_length=20)),
                ('factura_fecha', models.DateField()),
                ('factura_tipo', models.PositiveSmallIntegerField(choices=[(1, 'Contado'), (2, 'Créditos')], default=1)),
                ('factura_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('factura_total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=30)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'unique_together': {('descripcion', 'uc')},
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=30)),
                ('simbolo', models.CharField(help_text='Simbolo de la Moneda', max_length=3)),
                ('compras', models.IntegerField(default=0, help_text='Valor de compras', validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')])),
                ('ventas', models.IntegerField(default=0, help_text='Valor de ventas', validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')])),
                ('maestra', models.BooleanField(default=False, help_text='Moneda Maestra')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Monedas',
                'unique_together': {('simbolo', 'uc')},
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Sub Categoria', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistock.categoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Categorias',
                'unique_together': {('categoria', 'descripcion', 'uc')},
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('documento', models.CharField(help_text='RUC y/o CI N°', max_length=20)),
                ('razonsocial', models.CharField(help_text='Razón Social', max_length=100)),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=200, null=True)),
                ('contacto', models.CharField(help_text='Contacto', max_length=100)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=20, null=True)),
                ('email', models.CharField(blank=True, help_text='Teléfono', max_length=250, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'unique_together': {('documento', 'uc')},
            },
        ),
        migrations.CreateModel(
            name='ComprasDetalle',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('iva_valor', models.DecimalField(choices=[(1, 0), (2, 5), (3, 10)], decimal_places=2, default=3, max_digits=4)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_id', to='mistock.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistock.proveedor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ComprasDetalles',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_id', to='mistock.moneda'),
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistock.proveedor'),
        ),
        migrations.AddField(
            model_name='compras',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('codigo_barra', models.CharField(help_text='Código de Barra', max_length=50)),
                ('descripcion', models.CharField(help_text='Descripción del producto', max_length=200)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='fotos/')),
                ('detalle', models.CharField(blank=True, help_text='Detalle', max_length=250, null=True)),
                ('unidad', models.CharField(help_text='Unidad de Medidas', max_length=3)),
                ('existencia_inicial', models.FloatField(default=0, help_text='Existencia Inicial')),
                ('existencia_actual', models.FloatField(blank=True, default=0, help_text='Existencia Actual', null=True)),
                ('precio_costo', models.FloatField(default=0, help_text='Precio Costo')),
                ('precio_venta', models.FloatField(default=0, help_text='Precio Venta')),
                ('descuento_maximo', models.FloatField(default=0, help_text='Descuentos Máximo')),
                ('incremento_precio_credito', models.FloatField(default=0, help_text='Incremento Precio Crédito')),
                ('ultima_compra', models.DateField(blank=True, help_text='Fecha de Ultima Compra', null=True)),
                ('iva_valor', models.IntegerField(default=10)),
                ('servicio', models.BooleanField(default=False, help_text='Servicios')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistock.marca')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistock.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistock.proveedor')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mistock.subcategoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'unique_together': {('codigo_barra', 'uc')},
            },
        ),
    ]
