# Generated by Django 4.0.3 on 2022-05-26 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mistock', '0002_alter_moneda_descripcion_alter_moneda_simbolo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moneda',
            unique_together={('simbolo', 'uc')},
        ),
    ]
